services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    networks:
      - banking-web-app-network

  backend:
    image: webdevops/php-nginx:8.2-alpine
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      PHP_DATE_TIMEZONE: Asia/Bangkok
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: banking_web_app_db
      DB_USERNAME: root
      DB_PASSWORD: 2545
    depends_on:
      - database
    networks:
      - banking-web-app-network
    command: >
      sh -c "
      echo 'Starting Setup Process...';
      echo '--------------------------------------';
      
      echo '1. Checking Environment File...';
      echo '--------------------------------------';
      cp -n .env.example .env || true;      
      
      echo '2. Installing Dependencies...';
      echo '--------------------------------------';
      composer install --no-interaction --prefer-dist;
      
      echo '3ï¸. Generating App Key...';
      echo '--------------------------------------';
      php artisan key:generate --force;
      
      echo '4ï¸. Waiting for Database to be ready...';
      echo '--------------------------------------';
      sleep 30; 
      
      echo '5. Migrating & Seeding Database...';
      echo '--------------------------------------';
      php artisan migrate:fresh --seed --force;
      php artisan config:clear;
      php artisan cache:clear;
      
      echo '--------------------------------------';
      echo 'ðŸš€ Setup Complete! Starting Server...';
      echo '>>>>>>> http://localhost:3000/ <<<<<<<';
      echo '--------------------------------------';
      php artisan serve --host=0.0.0.0 --port=8000
      "

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: banking_web_app_db
      MYSQL_ROOT_PASSWORD: 2545
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - banking-web-app-network

networks:
  banking-web-app-network:
    driver: bridge

volumes:
  db_data: